### ISSUE TITLE
Compiler error with .replace method

### ISSUE THREAD

**Issue by Justin-Golden** [Adyen/CSE-JS#10]
I have been trying to use this, but am getting a javascript compiler error. I am using the adyen.encrypt.nodom.js file, and am having a problem with the ".replace" on line 400 (line number includes the current comments). I get the error "val.replace is not a function".

I tried replacing val = val.replace( /\D/g, '' ); with val = ("" + val).replace( /\D/g, '' ); and doing this in one other spot, but then the end result of the encrypted data always seems to be "false". Where am I going wrong?

**Comment by ArnoudAdyen** [comment]
H iJustin,

What is the data you are trying to get encrypted?

Regards,

Arnoud

**Comment by ArnoudAdyen** [comment]
Closing issue because no follow up.
