### ISSUE TITLE
ES6 modules + Babel

### ISSUE THREAD

**Issue by brunogarcia** [Adyen/CSE-JS#12]
Do you guys have a plan to create an ES6 module of this library?.
In our case, we use Webpack + Babel for compile those modules to ES5.

**Comment by ArnoudAdyen** [comment]
Hi Bruno,

There are no such plans, as in the long run we prefer Adyen hosted CSE over Merchant hosted CSE to be able to do keyrolling.

Regards,

Arnoud

**Comment by mishamaliga** [comment]
Since CSE-JS library is an AMD style module, you can use it in EcmaScript 6 code if you are using Webpack.
1. Add the CSE-JS library as a dependency in package.json (using GitHub repo):  
   
   ``` json
   "dependencies": {
     "adyen-cse-js": "git+https://github.com/Adyen/CSE-JS.git#v0.1.16"
   }
   ```
2. Use CSE-JS library in your code:  
   
   ``` javascript
   // EcmaScript 6 import
   import adyenEncrypt from 'adyen-cse-js';
   console.log(adyenEncrypt);
   ```
   
   ``` javascript
   // AMD style
   require(['adyen-cse-js'], function(adyenEncrypt) {
     console.log(adyenEncrypt);
   });
   ```
   
   ``` javascript
   // CommonJS style
   var adyenEncrypt = require('adyen-cse-js');
   console.log(adyenEncrypt);
   ```

**Comment by in2lag** [comment]
Problems are minification and dependencies, there are shimmed libs, which are loaded during dependency tree build (file gets 3 times bigger), of course solvable, but annoying...

edit: hidden dependency inside is `crypto`, so if you don't have it and you don't want to download whole package, add this to your webpack (2) config:

`externals: ['crypto']`

**Comment by mogelbrod** [comment]
Another solution for webpack is to tell it to not parse the package at all:
```js
// webpack.config.js
module.exports = {
  ...,
  noParse: [
    /node_modules\/adyen-cse-js/,
  ],
};
```
