### ISSUE TITLE
cseInstance.encrypt() returns false

### ISSUE THREAD

**Issue by vanhumbeecka** [Adyen/CSE-JS#14]
I'm not sure why this method returns false instead of returning the encrypted data.
I checked every input field and everything seems in order but I have no clue what I'm missing.

**Comment by ArnoudAdyen** [comment]
Hi,

Are you hosting the CSE library yourself, or using the hosted version from Adyen?

If the encryption is consistently returning `false`, then most likely a validation error happens.

As to debugging, given the limited information, I can suggest two routes you can take:
1. You might be able to get some additional information by examining the feedback of `cseInstance.validate()` and look if it gives any feedback.
2. Disable validations by setting `options.enableValidations=false` and see if you get data back. In this way we can bypass the validation logic completely. If you don't get any data back, then there is something in the encryption logic itself going wrong and we need to look further. If you do get data back and option 1 did not shed any light on the situation then we also need to dive further into the issue.

Regards,

Arnoud

**Comment by vanhumbeecka** [comment]
Thanks for clarifying. I'm hosting the library myself. It was as you say, due to a validation error. I didn't found the docs explaining it though, but this explains a lot.
