### ISSUE TITLE
Node module returns sjcl lib instead of adyen

### ISSUE THREAD

**Issue by agudulin** [Adyen/CSE-JS#16]
When I try to use no-dom version as a node module, I get the wrong object.

``` js
// package.json
"dependencies": {
  "adyen-cse-js": "git+https://github.com/Adyen/CSE-JS.git#v0.1.17"
}

// app.js
import adyenEncrypt from 'adyen-cse-js'
console.log(adyenEncrypt)
// → Object { cipher, hash, keyexchange, mode, misc, codec, exception, bitArray, prng, random, json, encrypt, decrypt }
```
### Why

Every node module has a `module` variable as a reference to the object representing the current module.

And I figured out that this variable is used in `sjcl` library, and you include this library into your module without any encapsulation.

As a result, when I import your library I get `sjcl` library instead.
### How to fix

You may want to wrap [this code](https://github.com/Adyen/CSE-JS/blob/master/js/adyen.encrypt.nodom.js#L149) into closure, and pass an empty object as `module` variable:

``` js
(function (module) {
  // ... current sjcl code on L149
})({});
```

Also [after defining AMD module](https://github.com/Adyen/CSE-JS/blob/master/js/adyen.encrypt.nodom.js#L172) it would be great to make it obvious what exactly do we want to export:

``` js
// L172
if (module && module.exports) {
  module.exports = encrypt;
}
```

**Comment by agudulin** [comment]
I've created corresponding PR for that: https://github.com/Adyen/CSE-JS/pull/17

**Comment by ArnoudAdyen** [comment]
Hi,

Why do you want to run CSE-JS as a node module? That would only be allowed if you (and/or the server processing the payment request from the browser) are fully PCI compliant. But then in that case you would not need encryption.

Maybe I am overlooking something. Can you explain your use case?

- Arnoud

**Comment by vkurlyan** [comment]
> if (module && module.exports) {

this code leads to the exception in a browser because 'module' is undefined

**Comment by agudulin** [comment]
@vkurlyan no, it does not :)

the second condition will never be executed if the first one is falsy.

so `if (undefined && undefined.exports) { ... }` will never show the execption

**Comment by agudulin** [comment]
however the corresponding PR has been already merged
and this issue can be closed

**Comment by vkurlyan** [comment]
If module is undefined we will have excaption because it's undefined variable but not property. You need to change code to do it without excaption:

> if (typeof module !== 'undefined' && module.exports)

**Comment by vkurlyan** [comment]
I added pull request https://github.com/Adyen/CSE-JS/pull/25

**Comment by agudulin** [comment]
@vkurlyan ah, I see, thanks!
