### ISSUE TITLE
error on all iOS devices in a cordova application

### ISSUE THREAD

**Issue by vanhumbeecka** [Adyen/CSE-JS#18]
I already made a github issue in another Adyen repository:
https://github.com/Adyen/client-side-encryption/issues/24

Everything works fine in an Android cordova application, but we get errors on the iOS cordova (multiple devices tested: iOS v9.2 and v9.3) which blocks our entire application (because no payments can be done on iOS)

Support ticket: LPC-669-89689

Please advice.

**Comment by vanhumbeecka** [comment]
I found the problem.
Wrote the solution in the referenced issue.

**Comment by aleixfargas** [comment]
Hi @vanhumbeecka, we are running into the same issue (ionic (cordova) application drop-in is not working for us only on iOS. Web and android is working correctly).

The link with the solution is broken, do you remember what was the problem? (And how to solve it) 
Thanks in advance! Cheers.

**Comment by vanhumbeecka** [comment]
Hi @aleixfargas 
That was a long time ago :) So unfortunately, I can't remember it. Too bad the link is broken.
Maybe contacting Adyen could help? Hope they have a backup of their issue list?
