### ISSUE TITLE
cvcIgnoreBins doesn't remove disabled unless you fire the CVC eventHandler

### ISSUE THREAD

**Issue by AlexGaspar** [Adyen/CSE-JS#21]
Hey,

I want to use `options.cvcIgnoreBins = '6703';` to Ignore CVC for BCMC but this options won't remove the `disabled` state form the submit button unless you click on the cvc field to fire the event handler.

Do you know why [here](https://github.com/Adyen/CSE-JS/blob/master/js/adyen.encrypt.js#L680-L693) we only update the validity of field who fired the event handler? 

We could update `cse.validity` with the result of `validate()`, like this ignored fields would also get updated.

```
cse.validity = cse.encryption.validate(validationData);

if ( validationResult[field] ) {
    removeClass( node, 'invalid-' + field );
    addClass( node, 'valid-' + field );
} else {
    if (!isInitializing || val !== '') {
        addClass( node, 'invalid-' + field );
    }
    removeClass( node, 'valid-' + field );
}
```

What do you think? Should I create a PR with this change ?
Alex

**Comment by ArnoudAdyen** [comment]
Hi,

This certainly makes sense. I will add it to a new release after running it through some new sets of unit tests. This will take me some time as I am currently occupied with non CSE related efforts.

Rgds,

Arnoud

**Comment by AlexGaspar** [comment]
Thanks Arnoud, 

If I can help in anyway you just ask!
