### ISSUE TITLE
Confirm support for browser, add it to documentation.

### ISSUE THREAD

**Issue by chodorowicz** [Adyen/CSE-JS#29]
I'd like to get a confirmation of supported browsers. IE10 gives an error.

```
There was an error collecting entropy from the browser: 
Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11 
```

So, it's official that Adyen CSE won't work in IE10 and below?
We could maybe add this info to the docs maybe?

**Comment by ArnoudAdyen** [comment]
In case that secure random number generation is not available the code tries to capture UI behavior for entropy collection. 
Are you lazy loading the library just before the stage where you do encryption? In which case the library does not get the UI input it needs for entropy collection?

**Comment by chodorowicz** [comment]
Hey @ArnoudAdyen! Thanks for your response.

It doesn't seem I'm calling it lazily.  So, my setup is following. I include Adyen CSE-JS in NPM `"adyen-cse-js": "git://github.com/Adyen/CSE-JS.git#v0.1.18"` and import it in one of my Webpack modules 

``` js
import adyenEncrypt from 'adyen-cse-js';
const getAdyenData = (adyenFields, adyenPayment) => {
  return adyenEncrypt.createEncryption(adyenPayment.clientSide.key, {}).encrypt(adyenFields);
}
export default {
  getAdyenData,
};
```

`getAdyenData` and `adyenEncrypt.createEncryption` are not called immediately, only when chosen and used as payment method, but anyway I get this error when whole bundle is loaded.

I'm loading the whole using `async="async"` - could that be the issue?

**Comment by ArnoudAdyen** [comment]
The collection is started by this call `sjcl.random.startCollectors();` in `adyen.encrypt.js#425`. So what you could try is call to `adyenEncrypt.createEncryption` early on. I think the `sjcl` library might not be exposed to the window object for you to call it directly.

**Comment by chodorowicz** [comment]
Hmm... I've only now tested the whole payment flow and it seems that it's working. My test payment got through. So, can be the case that this error is more of a notice, but CSE-JS still manages go gather entropy through UI? @ArnoudAdyen 
https://github.com/bitwiseshiftleft/sjcl/blob/master/core/random.js#L519
