### ISSUE TITLE
Add possibility to invalidate form in `onvalidate` hook

### ISSUE THREAD

**Issue by mieszko4** [Adyen/CSE-JS#30]
We have an adyen form that contains a confirmation checkbox (Terms) at the end and I want to be able to enable submit button only when this checkbox is checked.
If I could invalidate form in `onvalidate` hook that would be great.
I suggest that in the callback it could be done by simply returning `false` if one wants the form to be invalidated.

**Comment by mieszko4** [comment]
Then of the part of disabling submit button should be moved after `onvalidate` hook is fired.

**Comment by mieszko4** [comment]
One workaround to this problem is to check condition in `onvalidate` and reenable submit button.

**Comment by espudaro** [comment]
Hi @mieszko4,

In my work, we have the same problem. 
We need to enter with the anti-fraud fields in the adyen form. 
Have you solved this problem yet? What do you did?

**Comment by mieszko4** [comment]
@espudaro I did it with `ref`. In my case I wanted to make sure that checkbox for terms and conditions is checked.

```es
onvalidate: (e) => { // make sure submit is enabled only when agreedStatus is checked
  if (e.valid && !this.state.agreedStatus) {
    this.refs.submit.disabled = true;
  }
}

let btn = (<input
  type="submit"
  value="Send"
  disabled={!this.state.agreedStatus}
  ref="submit"
/>);
```
