### ISSUE TITLE
Adyen Hosted CSE is not gzipped

### ISSUE THREAD

**Issue by phil-r** [Adyen/CSE-JS#32]
[Google PageSpeed](https://developers.google.com/speed/pagespeed) is not happy with Adyen Hosted CSE, because content is not gzipped 

![image](https://cloud.githubusercontent.com/assets/577316/18552159/93628070-7b5b-11e6-8cd5-8ccb955d04d6.png)

**Comment by ArnoudAdyen** [comment]
Hi Phil,

Sorry for not responding. I'll put in a request on if we can enable gzip for the Hosted Payment Pages in general or the hosted CSE in specific. I can't promise on a ETA though.
- Arnoud

**Comment by phil-r** [comment]
@ArnoudAdyen Thanks!
