### ISSUE TITLE
Tag v0.1.18 fails to install properly using README

### ISSUE THREAD

**Issue by RyanMacG** [Adyen/CSE-JS#33]
Using the instructions in the README we ran into several issues getting the package to install using NPM for the v0.1.18 tag.

We eventually resolved this by using 
`"adyen-cse-js": "git+https://github.com/Adyen/CSE-JS.git#v0.1.18"`

**Comment by ArnoudAdyen** [comment]
I will add an instruction to replace the XX with the desired minor version.

**Comment by RyanMacG** [comment]
That's not the issue I was trying to identify sorry, the actual problem seems to be with the repo in the git url given it works with the old repo name

**Comment by ArnoudAdyen** [comment]
Thanks for getting back. I'll reopen the issue for now as I don't have time at the moment to look into this thoroughly.

**Comment by ArnoudAdyen** [comment]
It seems that this had to do to the wrong name being used in the `bower.json` and therefor the module being unpacked at `node_modules/adyen-cse-js` instead of `node_modules/adyen-cse-web`. I'm working on a patch to get that corrected, but need to run some more unit tests.
