### ISSUE TITLE
Cross Origin requests or JSONP

### ISSUE THREAD

**Issue by Marabyte** [Adyen/CSE-JS#36]
I've been searching the documentation but I couldn't find any information about CORS or JSONP.

Do I need to send any specific headers in my request?

The goal is to send  the encrypted card details and payment from the user's browser directly to Adyen servers.

Thank you

edit : typo

**Comment by ArnoudAdyen** [comment]
There is no such implementation option at the moment, nor is it planned. When you are using CSE, then you have filled out the SAQ-A form and should be able to send the encrypted data to your server, add the payment details and do a server to server call.

If you did not fill out the SAQ-A, then you should not be using CSE, but probably should be looking into Hosted Payment Pages instead.
