### ISSUE TITLE
Fail to validate

### ISSUE THREAD

**Issue by Marabyte** [Adyen/CSE-JS#37]
Hi all!

I'm having this issue but no ideia why.

``` js
let cardData = {
  cvc:"737",
  expiryMonth:"08",
  expiryYear:"2018",
  generationtime:"2016-10-10T17:01:16.748Z",
  holderName:"John Smith",
  number:"5555444433331111"
};

let encryptData = cseInstance.encrypt(cardData);
console.log(cseInstance.validate());
```

The console log returns false but there's no clue why the validation is failing.
Is there any way to enable a verbose mode for the validator?

Thank you,
Hugo

**Comment by ArnoudAdyen** [comment]
Hi Hugo,

The call to `cseInstance.validate()` requires you to pass in the `cardData`, otherwise it will early out.

You coud try to use `console.log( cseInstance.validate( cardData ) );` instead.

Kind regards,

Arnoud

**Comment by Marabyte** [comment]
Hi Arnoud,

Thank you for the tip! That helped but I'm still not sure why the validation fails.

``` js
{"valid":false,"number":true,"luhn":true,"cvc":true,"holderName":true,"month":true,"expiryMonth":true,"year":true,"expiryYear":true,"unknown":["generationtime","activate","initializeCount","luhnCount","luhnOkCount","luhnSameLengthCount","dfValue"]}
```

It seems the "generationtime" is either failing or not beeing recognised. I'm not sure if this is related with #27 

Thank you,
Hugo

**Comment by ArnoudAdyen** [comment]
Yes, both are related. I am still working into finalizing the fix towards that issue, but got caught up in other more work.

It's interesting that the luhnCount and other fields also are marked as unknowns. I didn't know they were passed into validation in the first place.
