### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by Joe-Withey** [Adyen/CSE-JS#39]
You guys have renamed your `package.json` name property in 5d253b7. Are you in the process of updating the github repo name also? It should match. Are you planning on publishing the library as a package on npm?

**Comment by ArnoudAdyen** [comment]
Hi,

The repository name was changed some time ago to be more consistent with other packages Adyen offers. The `package.json` and `bower.json` have been updated to reflect that change.

There are no plans currently to publishing the library as a package on npm, as we prefer merchants to use the hosted version of the library instead.

**Comment by Joe-Withey** [comment]
Sorry referenced the wrong commit d1a266cc26319f43c3d22bb0bc47b6cc263738d7. You've also updated the repository URL so you can confirm this is also going to change?

**Comment by chris-verclytte** [comment]
+1, it seems like a regression as d1a266c overwrite modifications made by 4423e3e earlier with wrong information (like git repo url for example).

**Comment by gilbarbara** [comment]
The repo is called `adyen-cse-web` but it creates a folder `adyen-cse-js` inside the node_modules.
What a mess! ¯\_(ツ)_/¯

Also both github and npm are hosted, I really can't understand the difference...

**Comment by ArnoudAdyen** [comment]
With Hosted CSE we mean the adyen hosted CSE in which your public key is embedded. This allows transparent keyrolling to happen, which is not possible when you use a github or npm hosted version and keep the public key in your server configuration. See the [HostedCSE.md](https://github.com/Adyen/adyen-cse-web/blob/master/HostedCSE.md)

**Comment by smolnikov** [comment]
Created #59 to make installation examples in readme work.
