### ISSUE TITLE
Why RSA+AES

### ISSUE THREAD

**Issue by viniciusnz** [Adyen/CSE-JS#4]
Sorry for my ignorance, but is there any reason for doing RSA+AES here, instead of pure RSA, given the message size will usually be much smaller than 245 chars? Is this for future proofing, or is it in any way more secure than just doing RSA?
Thanks!

**Comment by ArnoudAdyen** [comment]
Hi,

Had to forward the question internally, but it is quite possible we will be wanting to transfer larger messages in the near future and we don't want to be concerned about message size boundaries. For this reason we use RSA+AES.

There is no security benefit of using RSA+AES over RSA.

Regards,

Arnoud

**Comment by viniciusnz** [comment]
Ok Arnoud, thanks a lot for the response! That's what I thought then...

Sure message size is something you don't want to be worried about, but having simple RSA would lighten the load of the library quite a bit (maybe you could remove prgn4.js, rng.js, sjcl.js, sjcl.patch.js) and all the code related to generating a random AES key...

Obviously you do it how you want, I was just reading the code in detail and thinking about it, ok?
