### ISSUE TITLE
card number is incorrectly valid

### ISSUE THREAD

**Issue by rokerkony** [Adyen/CSE-JS#43]
Hi,
`validate()` method is returning valid true for credit card number: `23422343423443223432` which is really not valid as it doesn't start with numbers of any provider

**Comment by ArnoudAdyen** [comment]
You are correct in the sense that the library does not implement a bin lookup and only supplies syntax checks.
It's main goal is to prevent shoppers of mistyping their credit card number. Not to give a library that supplies a list of all valid bins.
