### ISSUE TITLE
require("crypto") in sjcl.js

### ISSUE THREAD

**Issue by PmegaOcalc** [Adyen/CSE-JS#44]
Due to require("crypto") in sjcl.js which is included in adyen.encrypt.js files when building a bundle with webpack a whole lot of dependencies are pulled in as a result. Unknowingly people who are using webpack or a similar bundling solution might be getting a bigger bundle as a result. This is unnecessary as the code which is responsible for the require fails silently in the browser.
The relevant line in the sjcl.js repo is here https://github.com/bitwiseshiftleft/sjcl/blob/00bd42dae9ebc3a28708db2053ffa2e88f99ad1e/core/random.js#L485
<img width="367" alt="screen shot 2016-12-02 at 17 03 19" src="https://cloud.githubusercontent.com/assets/603673/20838563/d7953394-b8b1-11e6-8d56-83c432258b43.png">
Adyen is 40KB~ in size parsed which leaves around 50KB~ of unwanted dependencies that start to get bundled with require("crypto").
My short term suggestion would be to remove the require("crypto") line in the adyen.encrypt.js files.

**Comment by ArnoudAdyen** [comment]
Hi,

We have no plans on refactoring the external libraries for this purpose. 

As a consideration. If you are concerned about file size, does it make sense to not webpack the library at all, and only (lazy) load the CSE library during your payments flow. There is little value in the library on all the other pages, which do not include your payments flow.

Regards,

Arnoud

**Comment by PmegaOcalc** [comment]
@ArnoudAdyen,

Thanks for the response. That is exactly what we did - lazy load the CSE library during payments.
Since you're not planning on refactoring you can close this issue.

**Comment by ArnoudAdyen** [comment]
In the end we prefer merchants to move to hosted CSE, as this eventually will allow us to start a smoother keyrolling procedure. In which case packaging the library as part of any build process would not be an option altogether.
