### ISSUE TITLE
[Question] _csrf in form body and Adyen

### ISSUE THREAD

**Issue by mauricionr** [Adyen/CSE-JS#49]
Hey guys 

I have an eCommerce built with NodeJS using adyen library in the client side and
after add [csurf](https://github.com/expressjs/csurf) library to protect the forms
 the last step in checkout(payment step) could not be completed.

my form has an input hidden like this one:
```HTML
<form method="POST">
    <input type="hidden" id="_csrf" name="_csrf" value="8cvViCIw-yTDZXYgPjA11VOaFCJG6W6Z7Sjk">
....adyen stuff
</form>
```

i have to setup something in adyen for this form work passing `_csrf` in the body?

Thanks!

**Comment by ArnoudAdyen** [comment]
Hi,

The Adyen library should not impact your hidden (or visible) input fields which are not part of the creditcard  input elements.

It will create an additional hidden input field at the bottom of your form, but other than that, your form should submit as normal.

Best,

Arnoud

**Comment by mauricionr** [comment]
Thanks
