### ISSUE TITLE
Elo Card type detection Fail

### ISSUE THREAD

**Issue by gpupo** [Adyen/CSE-JS#54]
ELO cards that are recognized as Maestro. Test samples:

    Card BRADESCO ELO MAIS: 5090510000414209
    Card B. BRASIL ELO NANQUIM: 5090685000041697
    Carb B. BRASIL ELO NANQUIM: 6516539999924898

ELO cards that are recognized as Discover. Test samples:

    Cart BRADESCO ELO GRAFITE: 6550049999924911

Check:
[RANGE_DE_BINS_ ELO_POR_PRODUTO (V 20161004).pdf](https://github.com/Adyen/adyen-cse-web/files/1026631/RANGE_DE_BINS_.ELO_POR_PRODUTO.V.20161004.pdf)

**Comment by ArnoudAdyen** [comment]
Hi,

Thanks for bringing this up. I'll check with the internal team to double check the numbers and see when they have time to add them on the platforms.

Just for completeness; The current list that is being used in the detection is 506699,50670,50671,50672,50673,50674,50675,50676,506770,506771,506772,506773,506774,506775,506776,506777,506778,401178,438935,451416,457631,457632,504175,627780,636297,636368, which indeed doesn't seem to include your example numbers.
