### ISSUE TITLE
react implementation?

### ISSUE THREAD

**Issue by bolicd** [Adyen/CSE-JS#55]
Hi,im trying to create working prototype in React however there are some issues im unable to solve. I've created java script page with HTML form and it works fine.Any help would be appreciated.

Not sure if im on the right track but I'm trying to apply encryption to the form and then execute form submit.

My form is
` <form id="adyen-encrypted-form" action="https://requestb.in/1mrymb71" method="POST" ref="AdyenForm">`

The onClick button event for the submit button is:
```
let options = {};
        // Bind encryption options to the form.
        let encrypted = window.adyen.createEncryptedForm(this.refs.AdyenForm, options);
        this.refs.AdyenForm.submit();
```

Im not getting any errors and im able to inspect window.adyen therefore it has been loaded successfully.

Line: `his.refs.AdyenForm.submit();` submits the form as it should.Problem is that for some reason form is not bound and encrypted as it should. Inspecting object:` window.adyen.encrypt.errors` i can see there is a `UNABLETOBIND:"CSEB01"`.

**Comment by ArnoudAdyen** [comment]
Hi,

The HTML form integration of the library is intended to be started / bound before the user interaction starts. 

The library itself will then make sure to add the hidden field with the encrypted data by listening/binding to the submit event of the form.

Regards,

Arnoud

**Comment by bolicd** [comment]
Yeah i guess I understand whats the issue now. 

I've got it working using `adyen.encrypt.nodom.min.js` so far, but will try with HTML form integration one more time as well.

Thanks

**Comment by ArnoudAdyen** [comment]
If you move to nodom, please check with your risk manager that it is okay to have reduced fraud prevention as nodom does not calculate a device fingerprint.
