### ISSUE TITLE
Broken card encryption after update to 0.1.20

### ISSUE THREAD

**Issue by klipach** [Adyen/CSE-JS#57]
When I try to send `paymentRequest.additionalData.card.encrypted.json` to https://pal-test.adyen.com/pal/adapter/httppost encrypted with latest js library (0.1.20) I'm getting a response from API 'validation 175 Unable to parse JSON data'

**Comment by ArnoudAdyen** [comment]
Thanks for the report. I will check what is going on.

**Comment by ArnoudAdyen** [comment]
Hi,

We are working on a fix, and will bring out a 0.1.20.1 in a few hours.

Regards,

Arnoud

**Comment by marcosbermejo** [comment]
Hi,

Only if someone finds this helpful:

In my project's bower.json I got this:

```
"adyen-cse-js": "^0.1.18",
```
And this doesn't see the version 0.1.20.1, it skips from 0.1.20 to 0.1.21

**Comment by janisbiz** [comment]
Yep, as @marcosbermejo mentioned - `Fatal error: Tag/branch ^0.1.20.1 does not exist`

**Comment by leonardo2204** [comment]
Was this ever fixed?
I'm still trying to use the "Encrypt" option, sending to the card.encrypted.json in additionalData but it returns {"status":422,"errorCode":"174","message":"Unable to decrypt data","errorType":"validation"}

I'm using the latest version.

**Comment by ArnoudAdyen** [comment]
It was fixed in 0.1.20.1
