### ISSUE TITLE
adyen.cardtype.determine returns "mc" when card number is undefined or ""

### ISSUE THREAD

**Issue by lauterry** [Adyen/CSE-JS#66]
Hello

In the file ```addOns.adyen.cardType.js``` line 61

```Cards.determine("")``` and ```Cards.determine(undefined)``` returns "mc".

I think this is not the expected behavior, right ?

If I'm wrong, please explain me why ?

I use this method to detect the cardType and show an icon in the input field depending on the credit card number

![capture d ecran 2017-12-11 a 10 29 46](https://user-images.githubusercontent.com/1374238/33824308-3d8c9430-de5e-11e7-9d68-d16ebe6a8cee.jpg)

Best regards

**Comment by ArnoudAdyen** [comment]
Yes. This seems wrong. Arguably there is no sense in calling the method at all in these scenarios, but the code needs to be more defensive about this. I'll have it fixed.

**Comment by lauterry** [comment]
Do you mean that I should not use this method for my scenario ?

**Comment by ArnoudAdyen** [comment]
Until it's fixed, it's indeed better to check for empty string and undefined in your own integration before calling the method.

**Comment by lauterry** [comment]
Yes this is what I have done until the fix is shipped :)

**Comment by lauterry** [comment]
Hi

Any news on this issue ?
