### ISSUE TITLE
Passing 2 digits year should be valid

### ISSUE THREAD

**Issue by lauterry** [Adyen/CSE-JS#67]
Hello

Most of the credit card in France displays 2 digits for the expiration year. (18 for 2018)

That's why my form allows to enter 2-digits year instead of 4-digits.

However, passing 2 digits year to the validate function seems to be invalid.

I expect a 2 digits year to passed as well as a 4 digits year.

What's your thoughts ?

Best regards

**Comment by pasfranc-dodax** [comment]
We have same issue here in Switzerland. No way to make it work with 2 digits for year.

I tried to make an hidden input for year, appending "20" to the value of year input on submit,  but it does not work, it seems the form it is encrypted before the submit.

Is there any way to achieve this?
