### ISSUE TITLE
Elo credit card is detected as maestro

### ISSUE THREAD

**Issue by codextremist** [Adyen/CSE-JS#7]
An Elo credit card is falsely detected as a maestro card (adyen-cardtype.js). You can check it by using the number provided in the documentation https://www.adyen.com/home/support/knowledgebase/implementation-articles 
Card number 5066 9911 1111 1118

**Comment by ArnoudAdyen** [comment]
Hi Felipe,

We are working on improving the card type detection, especially for dual branded (and even triple branded) cards. A minor patch is already planned for upcoming release, which will fix the ELO issue.

Kind regards.

**Comment by ArnoudAdyen** [comment]
Hi Felipe, 

The 0.1.15 release should resolve this issue. 

Kind regards,

Arnoud

**Comment by codextremist** [comment]
Thanks!
