### ISSUE TITLE
holder name is not validated

### ISSUE THREAD

**Issue by svewag** [Adyen/CSE-JS#8]
There seems to be a bug concerning the validation of the card holder name.

In `Encryption.prototype.encrypt` the `validationObject` does not contain the `holderName` key.

Is that correct?

Thanks for your feedback.

**Comment by svewag** [comment]
Any feedback here?

**Comment by ArnoudAdyen** [comment]
Sorry Sven for getting back to you so late. 

You are completely correct. I now have added this field and also updated the unit tests.

There are some more changes upcoming so I will not yet release just for this issue.

Kind regards,

Arnoud
