### ISSUE TITLE
Provide npm package (or add package.json to repo)

### ISSUE THREAD

**Issue by pbambusek** [Adyen/CSE-JS#9]
I'd like to get client side encryption nodom library as npm dependency for our project, so that copy of the file doesn't have to be in our repository.

Can you provide this?

**Comment by balthazar** [comment]
:+1:

**Comment by in2lag** [comment]
+1

**Comment by balthazar** [comment]
Just for reference, I created an [only-js lib](https://github.com/Apercu/adyen-encrypt), if you guys are interested.

**Comment by jirihelmich** [comment]
:+1: 

Nowadays, this is a "must have".

**Comment by ArnoudAdyen** [comment]
Hi,

Thank you @leafymind for adding this.

Please note that although you can host the library yourselves and this will certainly make the process easier, we do have to see on how to keep this included; We are looking into implementing a key-rolling mechanism that will automatically refresh/renew the public and private keys after a period of time. This refresh will be more efficient for implementations based on the Adyen hosted library.
When you host the library yourselves, it will be more difficult to keep the public and private keys in sync, even though we do take into account a certain grace period for old keys to expire.
For Adyen hosted keys this period can  obviously be significantly shorter than when a merchant hosted CSE is used, as no manual process and checks need to be performed and the main concerns are around how fast browsers and proxies can catch up with the changed key.

Thanks again Benni, very much appreciated,

Arnoud
